### ISSUE TITLE
code 11.6: kd bandwidth parameter needs changing

### ISSUE THREAD

**Issue by murphyk** [fehiepsi/rethinking-numpyro#13]
In code 11.6, if you use bw=0.3, it doesn't show the U-shaped curve of the prior predictive.
It is better to write just `az.plot_kde(p)`.

**Comment by fehiepsi** [comment]
Thank you, @murphyk! I'll address this problem soon. I am on the job market recently so a bit slow in responding to the issues.

**Comment by fehiepsi** [comment]
Thanks, @murphyk, I just fixed it. :)
