### ISSUE TITLE
Add quick tests to check numpyro version compatibility

### ISSUE THREAD

**Issue by neerajprad** [fehiepsi/rethinking-numpyro#2]
It will be nice if you had some quick tests to run that will validate that the examples run correctly with updates to NumPyro.

**Comment by fehiepsi** [comment]
Good idea, I'll add it. I think I can test all notebooks in Travis because it is pretty fast.

**Comment by fehiepsi** [comment]
I have used nbval to test all cells in Travis. The build passes now. Thanks for your suggestion!
