### ISSUE TITLE
Wrong code indexes - 5.23 to 5.54

### ISSUE THREAD

**Issue by felipeffm** [fehiepsi/rethinking-numpyro#23]
The code indexes from file 05_the_many_variables_and_the_spurious_waffles.ipynb, from 5.23 to 5.54,  are wrong by +1. 

The [pull request](https://github.com/fehiepsi/rethinking-numpyro/pull/22) would correct it.

**Comment by fehiepsi** [comment]
The current indices are expected. Do you mean there is a missing cell w.r.t. the book?

**Comment by felipeffm** [comment]
I may be comparing it with a different edition? The index is offset from +1, from code cell 5.23 to the end at the pdf I am reading .
 
 For example:
 ![Screenshot from 2023-02-01 08-16-45](https://user-images.githubusercontent.com/38499437/216029080-e23b8832-dee3-4eb1-9511-3297717670eb.png)


 (By the way, thank you for sharing the numpyro approach.)

**Comment by fehiepsi** [comment]
It seems to me that the cell numbers match the official release https://github.com/rmcelreath/rethinking/blob/783d111a2c70c534ee9e59ae024800290cc5ac48/book_code_boxes.txt#L951 maybe you are using a newer print?

**Comment by felipeffm** [comment]
You are right, my mistake.
