### ISSUE TITLE
Resolution of exercises

### ISSUE THREAD

**Issue by felipeffm** [fehiepsi/rethinking-numpyro#24]
Resolutions of the exercises could help those early learners following the book and this repo.

From the perspective of someone learning bayesian statistics and numpyro simultaneously, reading the book and following the examples in this repo is a bit challenging. 

Mainly because the documentation of numpyro methods used in the code examples utilizes terms from bayesian statistics yet to be explained by the book. It seems unlikely that the first three chapter exercises could be done without much effort from the code examples without previous bayesian statistics knowledge, just based on the code examples. At least, that has been my personal experience following the book and the repo. 

My intention is compile the solutions of all exercises of each chapter in numpyro in [GitHub](https://github.com/felipeffm/statistical-rethinking-resolutions) to help other readers.

What do you think about it? Would you already have the solutions in numpyro?

**Comment by fehiepsi** [comment]
Hi @felipeffm, resolutions are great! It's much better to explain things along with the code. I think we can add links to your work in each chapter for better explanation. What do you think?

**Comment by felipeffm** [comment]
I think that's a Great idea. So I will keep posting the exercises resolutions.

**Comment by felipeffm** [comment]
Hi @fehiepsi , sorry for the delay in providing the resolutions. 

I published them [here](https://github.com/felipeffm/statistical-rethinking-resolutions). Chapters 2 and 3 are complete.

I don't know where to add the link to resolutions in each chapter. Would you say at the end of each notebook or in .README? 

(I'll keep making the resolutions, I am currently in the middle of chapter 4. )

**Comment by fehiepsi** [comment]
Great work, @felipeffm! Re link: maybe add links to corresponding chapters at the beginning in each notebook and link to the repository some where in README - up to you (I prefer making them visible for readers). :)
