### ISSUE TITLE
Extra code section that should not be there?

### ISSUE THREAD

**Issue by kvaky** [fehiepsi/rethinking-numpyro#30]
In [notebooks/05_the_many_variables_and_the_spurious_waffles.ipynb](https://github.com/fehiepsi/rethinking-numpyro/blob/master/notebooks/05_the_many_variables_and_the_spurious_waffles.ipynb), there is code section `Code 5.23` which I think should not be there. Am I missing something? If you want, I can make a PR that removes this and fix the following code block numbers

**Comment by fehiepsi** [comment]
It seems to appear in [the official code](https://github.com/rmcelreath/rethinking/blob/master/book_code_boxes.txt#L880-L884).

**Comment by kvaky** [comment]
Interesting, in my version of the book (which I admit is a pdf I found online and says "This version compiled December 8, 2019") it's not there, sorry for that :)
