### ISSUE TITLE
Code 4.48 returns rank-1 solution for N >= 54

### ISSUE THREAD

**Issue by Drewniacki** [fehiepsi/rethinking-numpyro#32]
Chapter 4. Geocentric Models
4.4. Linear prediction
Code 4.48 (and Code 4.49 to display it)

Whenever N is equal or bigger than 54, sampled posterior returns rank-1 matrix (aka, all the rows are the same). Sounds like a numpyro package issue, but wanted to report it here since I cannot get to the bottom of it. Could you help?

![image](https://github.com/user-attachments/assets/c75aec72-7a51-4017-b779-9e86dde63b22)
![image](https://github.com/user-attachments/assets/ab7d758b-9c43-4a66-80d8-082de8f46b87)

**Comment by fehiepsi** [comment]
LaplaceApproximation requires a positive definite hessian matrix, which could be tricky to achieve for dimensional problems. You might want to enable double precision in that case: `numpyro.enable_x64()`

**Comment by fehiepsi** [comment]
Good to know that it worked! I guess we can close this issue.
